server:
  port: 8081
spring:
  application:
    name=companyapp
  data:
    mongodb:
#      uri: mongodb+srv://kedar:${mongodb.password}@true-caller-api-test.hdcue.mongodb.net/
      uri: mongodb://localhost:27017/
      database: trueCallerDB
spring-doc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method
    disable-swagger-default-url: true
  writer-with-default-pretty-printer: true
  default-produces-media-type: application/json
  override-with-generic-response: true

  
